@startuml Car
skinparam ClassAttributeIconSize 0
package Chapter.two.five{
    class Car
    class Vehicles
    Vehicles <|-- Car
}


class StartUp

Car<.StartUp

class StartUp{
    +main(args : String[]) : void
}
class Vehicles{
    -band : String
    -color : String
    +Vehicles(bandStr : String , colorStr : String)
    +CurrentSpeed() : double
    +getBand() : String
    +setBand(bandStr : String) : void
    +getcolor() : String
    +setcolor(colorStr : String) : void
    +showInfo() : void
}

class Car{
    -seats : int
    +Car(bandStr : String , colorStr : String, seatsValue : int)
    +CurrentSpeed() : double
    +getSeats() : int
    +setSeats(seatsNum : int) : void
    +showInfo() : void
}
@enduml